<h1>Berapa Biaya yang Harus Saya Keluarkan?</h1>
<h2>Biaya Pokok</h2>
<p>
Biaya pokok adalah biaya yang Anda keluarkan jika sudah mantap dan mempercayakan konsultasi tugas akhir Anda kepada saya. Dan, saya tidak akan berbasa-basi dalam hal ini: nilai jasa konsultasi saya terbilang cukup mahal. Tugas Akhir adalah perkara serius, dengan beban tekanan yang tinggi dan harus disikapi dengan seprofesional mungkin. Konsultasi rutin, revisi dosen, persiapan pendadaran dan revisi pasca pendadaran, kesemuanya itu membutuhkan dan mengkonsumsi stamina lahir maupun bathin yang luar biasa. Setelah bertahun-tahun memahami semua seluk-beluk jasa konsultasi tugas akhir ini, maka akhirnya saya bisa menemukan rumusan biaya yang akan menjamin terselesaikannya Tugas Akhir Anda dengan sempurna, yaitu :
<ol>
     <li>S1 = Rp. 3.500.000,00</li>
     <li>S2 = Rp. 6.500.000,00</li>
     <li>S3 = Rp. 9.500.000,00</li>
</ol>
<p>
     Biaya pokok ini harus dibayarkan dimuka sebesar 50%, dengan satu syarat yang wajib dipatuhi : biaya yang dikeluarkan, tidak bisa diminta kembali, apapun alasan yang melatarbelakanginya. Alasannya sederhana : saya bisa kelabakan kalau sampai ada fase harus mengembalikan uang muka. Berdasarkan pengalaman, hal itulah yang dulu sempat membuat saya enggan menekuni jasa konsultasi ini. :)
</p>
<p>
     Saya menyadari sekali ada yang memberi tarif jauh lebih murah, dan saya sudah pernah menjalani cara kerja seperti itu. Sangat luar biasa melelahkan bathin. Hasilnya? Akhirnya saya malah memilih mengembalikan DP yang sudah diberikan. Itu terjadi, karena dengan harga yang rendah, maka konsultan akan cenderung menambah klien untuk mendapatkan akumulasi income yang mencukupi. Padahal, menambah klian itu berarti menguras semua sumber daya konsultan itu sendiri. Karenanya, saya memberikan tarif yang tinggi, sehingga dengan satu atau dua klien saja dalam satu bulan, sudah mencukupi. Tentunya itu akan berimbas kepada keterjaminan penyelesaian skripsi, thesis atau disertasi Anda.
</p>
<h2>Biaya Pertemuan</h2>
      Pertemuan adalah konsultasi Anda dengan saya yang bertujuan untuk Anda menjelaskan kepada saya tentang aplikasi yang diinginkan, atau revisi dari dosen ataupun fitur baru yang ingin ditambahkan oleh dosen. Dulu, saya tidak menganggap ini sebagai kriteria yang harus dikenai biaya tambahan. Namun, akhirnya saya menyadari bahwa hal ini sama melelahkannya dengan kondisi jika harus mengembalikan DP. Maka, saya memberikan peraturan biaya pertemuan berikut ini:
<ol>
      <li>Untuk pertemuan reguler, Anda akan dikenai biaya Rp. 50.000/sekali datang, dengan durasi pertemuan maksimal 2 jam. Itu sudah sangat mencukupi. Rata-rata pertemuan klien-klien terdahulu, ada di rentang 10-15kali. Tentu ini sangat berbeda-beda tergantung kondisi berbagai faktor, diantaranya yang paling sering terjadi adalah : dosen yang .. minta macam-macam :). Pertemuan reguler disini adalah pertemuan yang bertujuan untuk menyelesaikan pengembangan aplikasi berdasarkan requirement di awal yang sudah disetujui. Pengalaman terburuk yang pernah saya hadapi adalah, requirement di awal dengan kenyataan di perjalanan pengembangannya adalah luar biasa berbeda. Ini yang berusaha saya hindari.</li>
                                                                                                                                                                                                                                                                                                                                                                                       <li>Untuk pertemuan yang bersifat pengembangan dari requirement, maka dengan berat hati saya terpaksa menaikkan tarif pertemuan menjadi Rp. 75.000,00/sekali pertemuan. Hal ini bisa mudah dihindari, dengan secara lengkap menyatakan apa requirement aplikasinya. Bayangkan jika di satu konsultasi, seorang klien memberikan requirement sejumlah 10butir, dan kode pun dirancang untuk mengimplementasikan 10butir tersebut. Namun kemudian ternyata ada 3 butir yang dihapus setelah ditambahkan, dan ada penambahan 6 butir baru. Itu laksana meminta tukang bangunan menggali kembali pondasi setelah bangunan lantai dua selesai. :)</li>
                                                                                                                                                                                                                                                                                                                                                                                       <li>Terakhir, untuk pertemuan yang bersifat revisi dari dosen setelah pendadaran (yang berarti aplikasi sudah tepat selesai sesuai requirement awal), maka dengan sangat terpaksa biaya per pertemuan saya naikkan menjadi Rp. 100.000,00. Namun kebiasaan yang dihadapi, hanya butuh sekali pertemuan saja jika memang dosen saat pendadaran meminta adanya perubahan aplikasi</li>
</ol>
</p>