<h1>Syarat dan Ketentuan</h1>
<p>
Terakhir, disini akan saya jelaskan bagaimana proses konsultasi dilaksanakan. Proses yang saya paparkan disini merupakan proses yang sudah mengalami berbagai revisi dan penambahan di sana-sini, berbekal pengalaman saya sebelumnya. Maka, yakinilah, bahwa ini lah jalan yang paling baik untuk mencapai penyelesaian Tugas Akhir yang sempurna.
</p>
<p>
     Adapun syarat dan ketentuan yang saya maksudkan adalah :
<ol>
     <li>Sangat lebih baik dan memudahkan, jika proses konsultasi ini berada di bawah persetujuan dan pengawasan orang tua. Secara umum memang demikian adanya, karena mahasiswa biasanya belum mampu membiayai dirinya sendiri. Namun saya pernah mengalami adanya klien yang merahasiakan proses konsultasi ini dari orangtuanya, akibatnya banyak hal-hal yang kurang nyaman terjadi :)</li>
     <li>Saya memang bertindak selaku Koder yang akan menyelesaikan pengembangan aplikasi Anda, namun jangan harap bahwa Anda akan tenang-tenang saja selama proses ini. Anda harus belajar dengan cepat. Ingat, ujian pendadaran bisa digagalkan dosen begitu melihat adanya ketidakcocokan antara kerumitan aplikasi yang dikembangkan dengan tingkat keahlian Anda pada bahasa pemrograman tersebut. Saya teringat, dulu ada seorang klien yang gagal pendadarannya, dikarenakan saat akan mendemokan aplikasinya, ia tidak sengaja mengk-klik tampilan dari Project View ke File View, di Netbeans. Walhasil, menu Run jadi tidak ada. Dan... 1jam mahasiswa ini berusaha mencari tombol Run tersebut. Kan tidak lucu jadinya... :) Syukur akhirnya mahasiswa ini masih dibolehkan mengikuti pendadaran ulang. </li>
     <li>Beranilah maju pendadaran! Saya memiliki tiga klien yang setelah saya bantu pengembangan software dan naskahnya, akhirnya malah maju mundur untuk sekedar ketemu dosen... Ya, bagaimana Anda mau pendadaran kalau sekedar bertemu dengan dosen saja tidak berani?</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <li>Manfaatkan pertemuan dan masa-masa pertemanan dengan saya sebaik-baiknya. Saya memiliki sedikit ilmu bermanfaat yang bisa saya turunkan kepada Anda. Karenanya, belajarlah bersama saya dalam proses kita mengembangkan aplikasi tersebut</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <li>Pertemuan dilakukan di kantor saya (yang juga adalah rumah saya), di dalam hari dan jam kerja. Sabtu-Minggu libur, tanpa ada perkecualian. Namun, karena saya juga memiliki banyak aktivitas diluar rumah (diantaranya aktivitas saya dengan Jama\'ah Tabligh yang memiliki masjid pertemuan di Jalan Kaliurang KM 5 dan intensitas saya berlatih Capoeira di GSP, UGM, maka saya bisa ditemui di hari-hari tersebut. Namun, pertemuan di luar rumah saya, tidak boleh yang sejatinya merupakan proses pembimbingan tugas akhir. Bolehlah, kalau sekedar menyerahkan bahan skripsi atau ... bonus :)</li>
         <li>Saya menjamin kerahasiaan identitas Anda, jika Anda menginginkannya. Karena, saya teringat ada kejadian lucu, dimana dosen (sedang mengambil S2 di UGM) dan mahasiswa (mengambil S1 di Universitas swasta) dari satu kampus yang sama, berada dalam satu periode konsultasi dengan saya. Dosen tersebut meminta sekali agar identitasnya dirahasiakan. Ya dengan senang hati saya lakukan itu. Namun, ada suatu kejadian dimana setelah saya atur agar datang di siang hari, ternyata mahasiswa ini justru datang di pagi hari. Syukur sekali dosen tersebut belum datang. Adik mahasiswa ini akhirnya tahu kalau salah satu dosennya ada yang saya bantu juga Tugas Akhirnya, dan dia mati-matian ingin tahu siapa identitas dosennya tersebut. Nah, sampai sekarang dia masih penasaran dan salah menebak terus. :)</li>
</ol>
         Akhir kata saya, pahamilah bahwa syarat dan ketentuan yang saya rumuskan ini semuanya demi kelangsungan dan keterjaminan proses penyelesaian bimbingan tugas akhir Anda secara sempurna.
</p>